import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import auth from '../services/Authentification/Authentication'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const REDIRECT_TO_LOGIN='/login'
  const router = useRouter();

  useEffect(() => {
    // if user not logged in, redirect
    if (!auth.getCurrentUser()) {
       router.push(REDIRECT_TO_LOGIN);
    } // eslint-disable-next-line
  }, []);
  const handleLogout=()=>{
    auth.logout()
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the   <a href="https://nextjs.org">Next.js Auth App</a>
        </h1>

        <p className={styles.description}>
          You're  :
          <code className={styles.code}>Logged IN</code>
        </p>

        <div className={styles.grid}>

          <a onClick={handleLogout} className={styles.card}>
            <h2>Logout</h2>
            <p>this is a random text to keep the css looks cool,
              sorry for not providing profile page
            </p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
